name: interact with Github API
on:
#  pull_request:
#  workflow_dispatch:
  pull_request:
#  push:
jobs:
#  permissions:
#    issues: write
  run-npm-test:
    runs-on: ubuntu-latest
    env:
        NODE_VERSION: 14
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
        - name: check version
          run: node -v
#  create-issue:
#    runs-on: ubuntu-latest
#    steps:
#        - id: step1
#          name: build output
#          run: echo 'sha=${GITHUB_SHA::7}' >> $GITHUB_OUTPUT
#        - name: curling
#          run: curl -L  -X POST  -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/m49n3t0/github-actions/issues   --data '{    "title": "Automated issue for commit: ${{ steps.step1.outputs.sha }}",    "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.step1.outputs.sha }}_."    }'   --fail
#
#
